college_data = {'College name': 'Kalapataru institute of technology', 'Location': 'Tiptur', 'department': ['CSE', 'ISE', 'AI-ML', 'MEC', 'CIVIL']}

time_table_of_cse = {'Monday': ['9 AM: Chemistry', '10 AM: IME', '11:15 AM: AI', '12:15 PM: Math'], 'Tuesday': ['9 AM: Maths', '10 AM: AI', '11:15 AM: Chemistry', '12:15 PM: Python'], 'Wednesday': ['9 AM: Python', '10 AM: Chemistry', '11:15 AM: Math'], 'Thursday': ['11:15 AM: Chemistry', '12:15 PM: Maths', '2:15 PM: English'], 'Friday': ['9 AM: IME', '10 AM: Math', '11:15 AM: Chemistry', '12:15 PM: AI'], 'Saturday': ['9 AM: AI', '10 AM: IC', '11:15 AM: IDT-Lab']}

lab_timetable = {'Monday': ['2:15pm to 4:15pm: A1 Batch Chemistry LAB', '2:15pm to 4:15pm: A2 Batch Python LAB'], 'Tuesday': ['2:15pm to 4:15pm: A2 Batch Chemistry LAB', '2:15pm to 4:15pm: A3 Batch Python LAB'], 'Thursday': ['9:00am to 11:00am: A1 Batch Python LAB', '9:00am to 11:00am: A3 Batch Chemistry LAB']}

exam_schedule = {'Maths': 'Jan 10, 2026', 'Chemistry': 'Jan 12, 2026', 'AI': 'Jan 15, 2026'}

classderooms = {'Chemistry': 'Room 101', 'IME': 'Room 102', 'AI': 'Room 103', 'Math': 'Room 104', 'Python': 'Room 105', 'IC': 'Room 106'}

cse_a = ['Aishwarya Choudappa Hosakatti', 'Akruthi Gs', 'Amulya Mp', 'Amulya R', 'Ananya Rao M', 'Ankita', 'Basavaraj Sajjan', 'Bharamagoudra Rajanigouda', 'Bharath H N', 'Bhoomika D T', 'Bhoomika Patel', 'Bhuvan Hs', 'Brunda', 'Byregowda O Y', 'Chaithra Hs', 'Chaithrashree Ds', 'Chandan Gowda M', 'Chandana R', 'Charitra N', 'Chinmay M', 'Chinmayi At', 'D Prajwal', 'Daniya Ca', 'Deekshith R K', 'Deekshitha Tm', 'Deepika Gr', 'Devika B Raj', 'Dhanush Hm', 'Darshan Hs', 'Dhyaan P', 'Divyashree L K', 'Fiza C F', 'Ganga R', 'Geeta', 'Geetha P', 'Ghanashree K S', 'Gourav N Gowda', 'Gowri T U', 'Hd Bindu', 'Harshitha Mp', 'Harshitha Nc', 'Hruthvik S V', 'Jeevan P', 'Jeevitha C', 'K Manoj Kumar', 'Karthik R Varahad', 'Kavana Vd', 'Keerthana B R']

cse_b = ["Keerthana R V", "Kiran Kumar Y L", "Kusuma", "Kusuma A S", "Kusuma P","Lavanya", "Laxmi Shivarudrappa Akki", "Likhitha", "Likith Gowda K R", "Madan S V", "Madhushree A", "Mamatha", "Mandara K R", "Mayur Patil", "Md Enamul Hasan", "Megha", "Mehak Tarannum", "Mitra M", "Mohan A", "Mohan H D", "Moksha M A", "Monisha S", "Nagaraj Omkareppa Konchigeri", "Nagaraju B", "Nanagouda Shivanagouda Patil", "Nandini Shivaraj Hegde", "Nikhil V D", "Nikhitha A V", "Nikitha K", "Nischitha H R", "Nisha Karabasappa Haromuchadi", "Nishchitha S P", "Pallavi N", "Pavan S", "PRAGNA S B", "Prajwal G", "Prathibha B S", "Prathiksha M", "Pratiksha", "Priya H A", "Priyanka G S", "Pushpa K B", "R C MANASA", "R Rakshitha", "Rachana M N", "Raksha H S", "RANGASWAMY S", "Rihan Pasha", "Rishik Vikhyath P", "Rishitha S"]

cse_c = ["Rohini J R", "Sai Vivek K N", "Samhitha Nag", "Sandesh H P", "Sanjana B C", "Sanjana B R", "Sanjana S", "Sanjini D", "Shashidhara S N", "Shrinivas K T", "Sinchana C S", "Sneha B", "Sofia", "Sohan T S", "Sona G N", "Spandan Gopal Naik", "Spoorthi R", "Suchitra", "Suhas B P", "Suhas T J", "Sukanya M G", "Swarnagowri P C", "Tejas D P", "Thrisha M Kumar", "Ullas K N", "Vandana P", "Varalakshmi B", "Varshitha H N", "Varun Kumar C G", "Vasanth H G", "Veena Nagappa G", "Vidya M", "Vikas M M", "Vinay H R", "Vinutha N S", "Vishnu T N", "Yamuna K P", "Yashas", "Yashaswini M H", "Yashaswini P"]
